// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// const SUPABASE_URL = "https://hfteylygjgemdxcvvssg.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmdGV5bHlnamdlbWR4Y3Z2c3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjMwMTEsImV4cCI6MjA2MzUzOTAxMX0.cgRw8R7AqmtxogCz-H0W07AWSliRLgDQxaSeCy0NlJg";

const SUPABASE_URL = "https://tohrbrpeygtiqqqkcvwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvaHJicnBleWd0aXFxcWtjdnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDM4NzYsImV4cCI6MjA2NDQ3OTg3Nn0.4ZAXb55TDXR5oqKJyFEkUB6Zd0aNuvs36OVrK6lmkQY"

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);